GET http://localhost:3000/quiz

###

GET http://localhost:3000/quiz/5f9478090085c231948e4bfb

###

POST http://localhost:3000/quiz
Content-Type: application/json

{
  "title": "What is the primary source of energy for Earth's climate system?",
  "choices": [
    {
      "name": "a",
      "content": "sadf"
    },
    {
      "name": "b",
      "content": "asdf"
    },
    {
      "name": "c",
      "content": "xcvz"
    },
    {
      "name": "d",
      "content": "vzxc"
    }
  ],
  "answer": "The Sun",
  "author": "Columbia_University"
}

###

DELETE http://localhost:3000/quiz/5f9478090085c231948e4bfb

###

PATCH http://localhost:3000/quiz/5f9478090085c231948e4bfb
Content-Type: application/json

{
  "title": "Climate Quiz 1 modified v2",
  "answer": "This is the answer 1 modified v2"
}